version: '3'
services:
  admin:
    command: [ "-c", "trap : INT TERM QUIT; sleep infinity & wait" ]
    entrypoint: /bin/bash
    image: coinbase/chainnode
    network_mode: host
    restart: always
  api:
    command: [ "./server" ]
    image: coinbase/chainnode
    network_mode: host
    restart: always
  worker:
    command: [ "./worker" ]
    image: coinbase/chainnode
    network_mode: host
    restart: always
  cron:
    command: [ "./cron" ]
    image: coinbase/chainnode
    network_mode: host
    restart: always
